
package vista;

import java.awt.Dimension;

import modelo.BaseDatos;
import modelo.Servicio;

/**
 *
 * @author Franco
 */
public class VentanaServicio extends javax.swing.JDialog
{
    private Servicio servicio;
    private BaseDatos bd;
    
    /** Creates new form VentanaTareaNueva */
    public VentanaServicio(java.awt.Frame parent, boolean modal, Servicio servicio, BaseDatos bd)
    {
        super(parent, modal);
        initComponents();
        this.buttonGroup1.add(this.jrbFijo);
        this.buttonGroup1.add(this.jrbHora);
        this.jtfCosto.setPreferredSize(new Dimension(50,19));
        this.jtfDesc.setPreferredSize(new Dimension(50,19));
        this.servicio = servicio;
        this.bd = bd;
        this.setSize(200, 500);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfDesc = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrbFijo = new javax.swing.JRadioButton();
        jrbHora = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfCosto = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 1));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Descripcion");
        jPanel1.add(jLabel1);

        jtfDesc.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfDescActionPerformed(evt);
            }
        });
        jPanel1.add(jtfDesc);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Tipo de servicio:");
        jPanel2.add(jLabel2);

        jrbFijo.setText("Fijo");
        jPanel2.add(jrbFijo);

        jrbHora.setText("Hora");
        jPanel2.add(jrbHora);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Costo:");
        jPanel3.add(jLabel3);
        jPanel3.add(jtfCosto);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel4.add(jbAceptar);

        getContentPane().add(jPanel4);

        pack();
    }//GEN-END:initComponents

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jbAceptarActionPerformed
    {//GEN-HEADEREND:event_jbAceptarActionPerformed
        // TODO add your handling code here:
        this.servicio.setDescripcion((this.jtfDesc.getText()));
        if (this.jrbFijo.isSelected())
            this.servicio.setTipo("Fijo");
        else
            if (this.jrbHora.isSelected())
                this.servicio.setTipo("Por hora");
        this.servicio.setCosto(Double.parseDouble(this.jtfCosto.getText()));
        this.bd.agregaServicio(this.servicio);
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jtfDescActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfDescActionPerformed
    {//GEN-HEADEREND:event_jtfDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDescActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JRadioButton jrbFijo;
    private javax.swing.JRadioButton jrbHora;
    private javax.swing.JTextField jtfCosto;
    private javax.swing.JTextField jtfDesc;
    // End of variables declaration//GEN-END:variables

}
