
package vista;

import controlador.Controlador;

import java.awt.Dimension;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import javax.swing.JPanel;
import javax.swing.JRadioButton;

import javax.swing.JTextField;

import modelo.BaseDatos;
import modelo.Usuario;

/**
 *
 * @author usuario
 */
public class VentanaUsuarioNuevo extends javax.swing.JDialog
{
    private Usuario usuario;
    private BaseDatos bd;
    /** Creates new form VentanaUsuarioNuevo */
    public VentanaUsuarioNuevo(java.awt.Frame parent, boolean modal,Usuario usuario,BaseDatos bd)
    {
        super(parent, modal);
        initComponents();
        this.jtfNombre.setPreferredSize(new Dimension(100,15));
        this.jtfTel.setPreferredSize(new Dimension(100,15));
        this.jtfUsuario.setPreferredSize(new Dimension(100,15));
        this.jtfEmail.setPreferredSize(new Dimension(100,15));
        this.jtfContra.setPreferredSize(new Dimension(100,15));
        this.usuario=usuario;
        this.bd = bd;
        this.setSize(200,200);
        this.setVisible(true);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfNombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jrbAdm = new javax.swing.JRadioButton();
        jrbCol = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jtfEmail = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtfContra = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtfTel = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(4, 2));

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel1.setText("Nombre y Apellido:");
        jPanel1.add(jLabel1);

        jtfNombre.setPreferredSize(new java.awt.Dimension(100, 19));
        jPanel1.add(jtfNombre);

        getContentPane().add(jPanel1);

        jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel2.setText("Perfil:");
        jPanel2.add(jLabel2);

        buttonGroup1.add(jrbAdm);
        jrbAdm.setText("Adminitstrador");
        jPanel2.add(jrbAdm);

        buttonGroup1.add(jrbCol);
        jrbCol.setText("Colaborador");
        jrbCol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbColActionPerformed(evt);
            }
        });
        jPanel2.add(jrbCol);

        getContentPane().add(jPanel2);

        jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Nombre de Usuario:");
        jPanel3.add(jLabel3);

        jtfUsuario.setPreferredSize(new java.awt.Dimension(100, 19));
        jtfUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(jtfUsuario);

        getContentPane().add(jPanel3);

        jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel4.setText("Email:");
        jPanel4.add(jLabel4);
        jPanel4.add(jtfEmail);

        getContentPane().add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel5.setText("Contraseña:");
        jPanel5.add(jLabel5);
        jPanel5.add(jtfContra);

        getContentPane().add(jPanel5);

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel6.setText("Teléfono:");
        jPanel6.add(jLabel6);
        jPanel6.add(jtfTel);

        getContentPane().add(jPanel6);

        jbAceptar.setText("Aceptar");
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });
        jPanel7.add(jbAceptar);

        getContentPane().add(jPanel7);

        pack();
    }//GEN-END:initComponents
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    public Usuario getUsuario() {
        return usuario;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setJLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getJLabel1() {
        return jLabel1;
    }

    public void setJLabel2(JLabel jLabel2) {
        this.jLabel2 = jLabel2;
    }

    public JLabel getJLabel2() {
        return jLabel2;
    }

    public void setJLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getJLabel3() {
        return jLabel3;
    }

    public void setJLabel4(JLabel jLabel4) {
        this.jLabel4 = jLabel4;
    }

    public JLabel getJLabel4() {
        return jLabel4;
    }

    public void setJLabel5(JLabel jLabel5) {
        this.jLabel5 = jLabel5;
    }

    public JLabel getJLabel5() {
        return jLabel5;
    }

    public void setJLabel6(JLabel jLabel6) {
        this.jLabel6 = jLabel6;
    }

    public JLabel getJLabel6() {
        return jLabel6;
    }

    public void setJPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JPanel getJPanel1() {
        return jPanel1;
    }

    public void setJPanel2(JPanel jPanel2) {
        this.jPanel2 = jPanel2;
    }

    public JPanel getJPanel2() {
        return jPanel2;
    }

    public void setJPanel3(JPanel jPanel3) {
        this.jPanel3 = jPanel3;
    }

    public JPanel getJPanel3() {
        return jPanel3;
    }

    public void setJPanel4(JPanel jPanel4) {
        this.jPanel4 = jPanel4;
    }

    public JPanel getJPanel4() {
        return jPanel4;
    }

    public void setJPanel5(JPanel jPanel5) {
        this.jPanel5 = jPanel5;
    }

    public JPanel getJPanel5() {
        return jPanel5;
    }

    public void setJPanel6(JPanel jPanel6) {
        this.jPanel6 = jPanel6;
    }

    public JPanel getJPanel6() {
        return jPanel6;
    }

    public void setJPanel7(JPanel jPanel7) {
        this.jPanel7 = jPanel7;
    }

    public JPanel getJPanel7() {
        return jPanel7;
    }

    public void setJbAceptar(JButton jbAceptar) {
        this.jbAceptar = jbAceptar;
    }

    public JButton getJbAceptar() {
        return jbAceptar;
    }

    public void setJrbAdm(JRadioButton jrbAdm) {
        this.jrbAdm = jrbAdm;
    }

    public JRadioButton getJrbAdm() {
        return jrbAdm;
    }

    public void setJrbCol(JRadioButton jrbCol) {
        this.jrbCol = jrbCol;
    }

    public JRadioButton getJrbCol() {
        return jrbCol;
    }

    public void setJtfContra(JTextField jtfContra) {
        this.jtfContra = jtfContra;
    }

    public JTextField getJtfContra() {
        return jtfContra;
    }

    public void setJtfEmail(JTextField jtfEmail) {
        this.jtfEmail = jtfEmail;
    }

    public JTextField getJtfEmail() {
        return jtfEmail;
    }

    public void setJtfNombre(JTextField jtfNombre) {
        this.jtfNombre = jtfNombre;
    }

    public JTextField getJtfNombre() {
        return jtfNombre;
    }

    public void setJtfTel(JTextField jtfTel) {
        this.jtfTel = jtfTel;
    }

    public JTextField getJtfTel() {
        return jtfTel;
    }

    public void setJtfUsuario(JTextField jtfUsuario) {
        this.jtfUsuario = jtfUsuario;
    }

    public JTextField getJtfUsuario() {
        return jtfUsuario;
    }
    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfUsuarioActionPerformed
    {//GEN-HEADEREND:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jrbColActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jrbColActionPerformed
    {//GEN-HEADEREND:event_jrbColActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbColActionPerformed

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        // TODO add your handling code here:
        this.usuario.setNombre_apellido(this.jtfNombre.getText());
        this.usuario.setContraseña(this.jtfContra.getText());
        this.usuario.setNombre_de_usuario(this.jtfUsuario.getText());
        this.usuario.setEmail(this.jtfEmail.getText());
        if (this.jrbAdm.isSelected())
            this.usuario.setPerfil("Administrador");
        else
            if (this.jrbCol.isSelected())
                this.usuario.setPerfil("Colaborador");
        this.usuario.setTelefono(this.jtfTel.getText());
        this.bd.agregaUsuario(this.usuario);
        this.bd.guardarBase();
        this.dispose();
    }//GEN-LAST:event_jbAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JRadioButton jrbAdm;
    private javax.swing.JRadioButton jrbCol;
    private javax.swing.JTextField jtfContra;
    private javax.swing.JTextField jtfEmail;
    private javax.swing.JTextField jtfNombre;
    private javax.swing.JTextField jtfTel;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

}
