
package vista;

import java.awt.Dimension;

import modelo.Tarea;

/**
 *
 * @author usuario
 */
public class VentanaPrincipal extends javax.swing.JFrame
{

    /** Creates new form VentanaPrincipal */
    public VentanaPrincipal()
    {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents()//GEN-BEGIN:initComponents
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtfContrasena = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jbIniciaSesion = new javax.swing.JButton();
        jbCreaUsuario = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jcbInformes = new javax.swing.JComboBox<>();
        jbGeneraInf = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jlTareas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaInformes = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        jPanel2.setBackground(new java.awt.Color(153, 204, 255));
        jPanel2.setLayout(new java.awt.GridLayout(3, 2));

        jLabel1.setText("Usuario:");
        jPanel4.add(jLabel1);

        jtfUsuario.setPreferredSize(new java.awt.Dimension(90, 19));
        jtfUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfUsuarioActionPerformed(evt);
            }
        });
        jPanel4.add(jtfUsuario);

        jPanel2.add(jPanel4);

        jLabel2.setText("Contraseña:");
        jPanel5.add(jLabel2);

        jtfContrasena.setPreferredSize(new java.awt.Dimension(90, 19));
        jtfContrasena.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jtfContrasenaActionPerformed(evt);
            }
        });
        jPanel5.add(jtfContrasena);

        jPanel2.add(jPanel5);

        jbIniciaSesion.setText("Iniciar Sesion");
        jPanel6.add(jbIniciaSesion);

        jbCreaUsuario.setText("Crear Usuario");
        jPanel6.add(jbCreaUsuario);

        jPanel2.add(jPanel6);

        jPanel1.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));
        jPanel3.add(jPanel8);

        jcbInformes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Total de tareas", "Tareas Colaborador", "Estado de tareas", "Tareas Usuario" }));
        jcbInformes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcbInformesActionPerformed(evt);
            }
        });
        jPanel10.add(jcbInformes);

        jbGeneraInf.setText("Generar Informe");
        jPanel10.add(jbGeneraInf);

        jPanel3.add(jPanel10);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(1, 2));

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Tareas"));
        jScrollPane2.setToolTipText("");

        jScrollPane2.setViewportView(jlTareas);

        jPanel7.add(jScrollPane2);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informes"));

        jtaInformes.setColumns(20);
        jtaInformes.setRows(5);
        jScrollPane1.setViewportView(jtaInformes);

        jPanel7.add(jScrollPane1);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }//GEN-END:initComponents

    private void jcbInformesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcbInformesActionPerformed
    {//GEN-HEADEREND:event_jcbInformesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbInformesActionPerformed

    private void jtfUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfUsuarioActionPerformed
    {//GEN-HEADEREND:event_jtfUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfUsuarioActionPerformed

    private void jtfContrasenaActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jtfContrasenaActionPerformed
    {//GEN-HEADEREND:event_jtfContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfContrasenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing
                                                                   .UIManager
                                                                   .getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing
                         .UIManager
                         .setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util
                .logging
                .Logger
                .getLogger(VentanaPrincipal.class.getName())
                .log(java.util
                         .logging
                         .Level
                         .SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt
            .EventQueue
            .invokeLater(new Runnable()
            {
                public void run()
                {
                    new VentanaPrincipal().setVisible(true);
                }
            });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbCreaUsuario;
    private javax.swing.JButton jbGeneraInf;
    private javax.swing.JButton jbIniciaSesion;
    private javax.swing.JComboBox<String> jcbInformes;
    private javax.swing.JList<Tarea> jlTareas;
    private javax.swing.JTextArea jtaInformes;
    private javax.swing.JTextField jtfContrasena;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables

}
